datasource:
  db-cooperation:
    hikari:
      driver-class-name: org.postgresql.Driver
      jdbc-url: "${DATASOURCE_URL}"
      username: "${DATASOURCE_USERNAME}"
      password: "${DATASOURCE_PASSWORD}"
      connection-timeout: 60000
      maximum-pool-size: 5
spring:
  liquibase:
    enabled: true
    change-log: classpath:db.changelog-master.xml
    drop-first: false
